import { uniqueId } from 'lodash';

import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconAppWindow,
  IconNotebook,
  IconFileCheck,
  IconChartHistogram,
  IconChartPie2,
  IconChartScatter,
  IconChartPpf,
  IconChartArcs3,
  IconListTree,
  IconDashboard,
  IconUsers,
  IconBuilding,
  IconShield,
  IconDatabase,
  IconWorld,
  IconDeviceMobile,
  IconChartBar,
  IconAlertTriangle,
  IconCheck,
  IconX,
  IconClock,
  IconRefresh,
  IconDownload,
  IconUpload,
  IconSearch,
  IconFilter,
  IconInfoCircle,
  IconTrendingUp,
  IconTrendingDown,
  IconActivity,
  IconFileText,
  IconCalculator,
  IconReceipt2,
  IconCreditCard,
  IconWallet,
  IconQrcode,
  IconFingerprint,
  IconLock,
  IconKey,
  IconCertificate,
  IconShieldCheck,
  IconShieldX,
  IconShieldLock,
  IconShieldOff,
  IconBrain,
  IconDeviceLaptop,
  IconNetwork,
  IconServer,
  IconCloud,
  IconBlockquote,
  IconReportAnalytics,
} from '@tabler/icons-react';

const Menuitems = [
  {
    navlabel: true,
    subheader: '🏠 Dashboard & Overview',
  },
  {
    id: uniqueId(),
    title: 'Admin Dashboard',
    icon: IconDashboard,
    href: '/dashboards/enhanced-modern',
  },
  // {
  //   id: uniqueId(),
  //   title: 'Modern Dashboard',
  //   icon: IconLayout,
  //   href: '/dashboards/modern',
  // },

  {
    navlabel: true,
    subheader: '👥 Taxpayer Management',
  },
  {
    id: uniqueId(),
    title: 'Taxpayer Identity',
    icon: IconUserCircle,
    href: '/user-profile',
    children: [
      {
        id: uniqueId(),
        title: 'Taxpayers',
        icon: IconPoint,
        href: '/taxpayer-registration',
      },
    ],
  },

  {
    navlabel: true,
    subheader: '📊 Tax Operations',
  },
  {
    id: uniqueId(),
    title: 'Tax Assessment',
    icon: IconFileCheck,
    children: [
      {
        id: uniqueId(),
        title: 'All Assessments',
        icon: IconPoint,
        href: '/apps/assessment/list',
      },
      {
        id: uniqueId(),
        title: 'By Taxpayer',
        icon: IconPoint,
        href: '/apps/assessment/by-taxpayer',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Tax Payment',
    icon: IconCreditCard,
    href: '/tax/payments/list',
    children: [
      {
        id: uniqueId(),
        title: 'Payment List',
        icon: IconPoint,
        href: '/tax/payments/list',
      },
      // {
      //   id: uniqueId(),
      //   title: 'Payment Processing',
      //   icon: IconPoint,
      //   href: '/apps/payment/process',
      // },
      // {
      //   id: uniqueId(),
      //   title: 'Payment History',
      //   icon: IconPoint,
      //   href: '/apps/payment/history',
      // },
    ],
  },
  {
    id: uniqueId(),
    title: 'EFD Transactions',
    icon: IconReceipt2,
    href: '/apps/invoice/list',
    children: [
      {
        id: uniqueId(),
        title: 'Transaction List',
        icon: IconPoint,
        href: '/apps/invoice/list',
      },
      {
        id: uniqueId(),
        title: 'Create Invoice',
        icon: IconPoint,
        href: '/apps/invoice/create',
      },
      {
        id: uniqueId(),
        title: 'Invoice Details',
        icon: IconPoint,
        href: '/apps/invoice/detail/:id',
      },
    ],
  },

  {
    navlabel: true,
    subheader: '🔍 Compliance & Auditing',
  },
  // {
  //   id: uniqueId(),
  //   title: '🚀 Hyperledger Demo',
  //   icon: IconDatabase,
  //   href: '/apps/hyperledger-tax-demo',
  // },
  {
    id: uniqueId(),
    title: 'Compliance Monitoring',
    icon: IconShieldCheck,
    href: '/apps/compliance',
    children: [
      {
        id: uniqueId(),
        title: 'Compliance Dashboard',
        icon: IconPoint,
        href: '/apps/compliance',
      },

      {
        id: uniqueId(),
        title: 'Compliance Reports',
        icon: IconPoint,
        href: '/apps/compliance/reports',
      },
      {
        id: uniqueId(),
        title: 'Taxpayer Report',
        icon: IconFileDescription,
        href: '/apps/compliance/taxpayer-report',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Enterprise Audit',
    icon: IconShieldCheck,
    children: [
      {
        id: uniqueId(),
        title: 'Audit Logs',
        icon: IconPoint,
        href: '/apps/audit/logs',
      },
      {
        id: uniqueId(),
        title: 'High-Risk Transactions',
        icon: IconPoint,
        href: '/apps/audit/high-risk',
      },
      {
        id: uniqueId(),
        title: 'Audit Statistics',
        icon: IconPoint,
        href: '/apps/audit/statistics',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Legacy Auditing',
    icon: IconFileCheck,
    href: '/tax/auditing/list',
    children: [
      {
        id: uniqueId(),
        title: 'Audit List',
        icon: IconPoint,
        href: '/tax/auditing/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Reports',
    icon: IconReportAnalytics,
    href: '/apps/reports',
    children: [
      {
        id: uniqueId(),
        title: 'All Reports',
        icon: IconPoint,
        href: '/apps/reports',
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: 'VAT Management',
  //   icon: IconCalculator,
  //   href: '/apps/vat',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'VAT Dashboard',
  //       icon: IconPoint,
  //       href: '/apps/vat',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'VAT Returns',
  //       icon: IconPoint,
  //       href: '/apps/vat/returns',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'VAT Reports',
  //       icon: IconPoint,
  //       href: '/apps/vat/reports',
  //     },
  //   ],
  // },

  // {
  //   navlabel: true,
  //   subheader: '⛓️ Blockchain & Technology',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Blockchain Explorer',
  //   icon: IconDatabase,
  //   href: '/apps/blockchain',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Blockchain Dashboard',
  //       icon: IconPoint,
  //       href: '/apps/blockchain',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Transaction Explorer',
  //       icon: IconPoint,
  //       href: '/apps/blockchain/transactions',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'System Integration',
  //   icon: IconNetwork,
  //   href: '/apps/integration',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Integration Status',
  //       icon: IconPoint,
  //       href: '/apps/integration/status',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'API Management',
  //       icon: IconPoint,
  //       href: '/apps/integration/api',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Data Sync',
  //       icon: IconPoint,
  //       href: '/apps/integration/sync',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Smart Tax Chain Simulation',
  //   icon: IconActivity,
  //   href: '/simulation',
  //   chip: 'Demo',
  //   chipColor: 'success',
  // },

  // {
  //   navlabel: true,
  //   subheader: '📈 Analytics & Reports',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Revenue Analytics',
  //   icon: IconChartBar,
  //   href: '/analytics/revenue',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Revenue Dashboard',
  //       icon: IconPoint,
  //       href: '/analytics/revenue',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Revenue Trends',
  //       icon: IconPoint,
  //       href: '/analytics/revenue/trends',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Revenue Reports',
  //       icon: IconPoint,
  //       href: '/analytics/revenue/reports',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Performance Metrics',
  //   icon: IconTrendingUp,
  //   href: '/analytics/performance',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Performance Dashboard',
  //       icon: IconPoint,
  //       href: '/analytics/performance',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'KPI Tracking',
  //       icon: IconPoint,
  //       href: '/analytics/performance/kpi',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Performance Reports',
  //       icon: IconPoint,
  //       href: '/analytics/performance/reports',
  //     },
  //   ],
  // },

  {
    navlabel: true,
    subheader: '⚙️ System Management',
  },
  {
    id: uniqueId(),
    title: 'User Management',
    icon: IconUsers,
    href: '/system/users',
    children: [
      {
        id: uniqueId(),
        title: 'All Users',
        icon: IconPoint,
        href: '/apps/user/list',
      },
      {
        id: uniqueId(),
        title: 'User List',
        icon: IconPoint,
        href: '/system/users',
      },
      {
        id: uniqueId(),
        title: 'Role Management',
        icon: IconPoint,
        href: '/system/users/roles',
      },
      {
        id: uniqueId(),
        title: 'Permissions',
        icon: IconPoint,
        href: '/system/users/permissions',
      },
      {
        id: uniqueId(),
        title: 'Data Integrity',
        icon: IconPoint,
        href: '/apps/user/integrity',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Tax Type Management',
    icon: IconCalculator,
    href: '/system/tax-types',
    children: [
      {
        id: uniqueId(),
        title: 'All Tax Types',
        icon: IconPoint,
        href: '/system/tax-types',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'System Settings',
    icon: IconSettings,
    href: '/system/settings',
    children: [
      {
        id: uniqueId(),
        title: 'General Settings',
        icon: IconPoint,
        href: '/system/settings',
      },
      {
        id: uniqueId(),
        title: 'Security Settings',
        icon: IconPoint,
        href: '/system/settings/security',
      },
      {
        id: uniqueId(),
        title: 'Notification Settings',
        icon: IconPoint,
        href: '/system/settings/notifications',
      },
      {
        id: uniqueId(),
        title: 'Log Management',
        icon: IconFileDots,
        href: '/system/log-management',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Account Settings',
    icon: IconUserCircle,
    href: '/pages/account-settings',
  },

  // {
  //   navlabel: true,
  //   subheader: '📋 Communication & Support',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Email',
  //   icon: IconMail,
  //   href: '/apps/email',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Chat',
  //   icon: IconMessage2,
  //   href: '/apps/chats',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Tickets',
  //   icon: IconTicket,
  //   href: '/apps/tickets',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'FAQ',
  //   icon: IconHelp,
  //   href: '/pages/faq',
  // },

  // {
  //   navlabel: true,
  //   subheader: '🛠️ Development Tools',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'UI Components',
  //   icon: IconBox,
  //   href: '/ui-components/alert',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Alert',
  //       icon: IconPoint,
  //       href: '/ui-components/alert',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Accordion',
  //       icon: IconPoint,
  //       href: '/ui-components/accordion',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Avatar',
  //       icon: IconPoint,
  //       href: '/ui-components/avatar',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Chip',
  //       icon: IconPoint,
  //       href: '/ui-components/chip',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Dialog',
  //       icon: IconPoint,
  //       href: '/ui-components/dialog',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'List',
  //       icon: IconPoint,
  //       href: '/ui-components/list',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Popover',
  //       icon: IconPoint,
  //       href: '/ui-components/popover',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Rating',
  //       icon: IconPoint,
  //       href: '/ui-components/rating',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Tabs',
  //       icon: IconPoint,
  //       href: '/ui-components/tabs',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Tooltip',
  //       icon: IconPoint,
  //       href: '/ui-components/tooltip',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Transfer List',
  //       icon: IconPoint,
  //       href: '/ui-components/transfer-list',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Typography',
  //       icon: IconPoint,
  //       href: '/ui-components/typography',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Charts',
  //   icon: IconChartLine,
  //   href: '/charts/line-chart',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Line Chart',
  //       icon: IconPoint,
  //       href: '/charts/line-chart',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Area Chart',
  //       icon: IconPoint,
  //       href: '/charts/area-chart',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Column Chart',
  //       icon: IconPoint,
  //       href: '/charts/column-chart',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Doughnut Chart',
  //       icon: IconPoint,
  //       href: '/charts/doughnut-pie-chart',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Radialbar Chart',
  //       icon: IconPoint,
  //       href: '/charts/radialbar-chart',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Candlestick Chart',
  //       icon: IconPoint,
  //       href: '/charts/candlestick-chart',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Tables',
  //   icon: IconBorderAll,
  //   href: '/tables/basic',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Basic Table',
  //       icon: IconPoint,
  //       href: '/tables/basic',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Enhanced Table',
  //       icon: IconPoint,
  //       href: '/tables/enhanced',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Collapsible Table',
  //       icon: IconPoint,
  //       href: '/tables/collapsible',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Fixed Header Table',
  //       icon: IconPoint,
  //       href: '/tables/fixed-header',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Pagination Table',
  //       icon: IconPoint,
  //       href: '/tables/pagination',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Search Table',
  //       icon: IconPoint,
  //       href: '/tables/search',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Forms',
  //   icon: IconFileDescription,
  //   href: '/forms/form-elements/autocomplete',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Form Elements',
  //       icon: IconPoint,
  //       href: '/forms/form-elements/autocomplete',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Form Layouts',
  //       icon: IconPoint,
  //       href: '/forms/form-layouts',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Form Validation',
  //       icon: IconPoint,
  //       href: '/forms/form-validation',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Form Wizard',
  //       icon: IconPoint,
  //       href: '/forms/form-wizard',
  //     },
  //   ],
  // },
];

export default Menuitems;
